# Generated by Django 4.0.1 on 2022-01-12 12:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.IntegerField()),
                ('doctor_id', models.IntegerField()),
                ('examination', models.TextField()),
                ('investigation', models.TextField()),
                ('diagnosis', models.TextField()),
                ('advice', models.TextField()),
                ('comment', models.TextField()),
                ('chief_complain', models.TextField()),
                ('active', models.BooleanField(default=True)),
                ('date', models.DateField(default=datetime.datetime(2022, 1, 12, 12, 35, 27, 842639))),
            ],
        ),
    ]
