# Generated by Django 4.0.1 on 2022-01-13 08:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_prescription_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_id', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('firstname', models.CharField(max_length=40)),
                ('lastname', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=40)),
                ('qualification', models.CharField(max_length=40)),
                ('specialization', models.CharField(max_length=40)),
                ('dob', models.DateField()),
                ('phone_no', models.PositiveBigIntegerField()),
                ('gender', models.CharField(max_length=5)),
                ('registration_no', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='prescription',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 1, 13, 8, 11, 23, 200079)),
        ),
    ]
