# Generated by Django 4.0.1 on 2022-01-13 07:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Medication_id', models.IntegerField()),
                ('prescription_id', models.IntegerField()),
                ('medication_item', models.TextField()),
                ('strength', models.TextField()),
                ('preparation', models.TextField()),
                ('route', models.TextField()),
                ('dose', models.TextField()),
                ('dorection', models.TextField()),
                ('frequency', models.BooleanField(default=True)),
                ('duration', models.DateField(default=datetime.datetime(2022, 1, 13, 7, 33, 35, 907004))),
                ('total_quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.IntegerField()),
                ('doctor_id', models.IntegerField()),
                ('examination', models.TextField()),
                ('investigation', models.TextField()),
                ('diagnosis', models.TextField()),
                ('advice', models.TextField()),
                ('comment', models.TextField()),
                ('chief_complain', models.TextField()),
                ('active', models.BooleanField(default=True)),
                ('date', models.DateField(default=datetime.datetime(2022, 1, 13, 7, 33, 35, 906573))),
            ],
        ),
    ]
