# Generated by Django 4.0.1 on 2022-01-12 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_id', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('firstname', models.CharField(max_length=40)),
                ('lastname', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=40)),
                ('qualification', models.CharField(max_length=40)),
                ('specialization', models.CharField(max_length=40)),
                ('dob', models.DateField()),
                ('phone_no', models.PositiveBigIntegerField()),
                ('gender', models.CharField(max_length=5)),
                ('registration_no', models.IntegerField()),
            ],
        ),
    ]
