# Generated by Django 4.0.1 on 2022-01-13 08:47

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_remove_doctor_doctor_id_alter_doctor_email'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='doctor',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
