# Generated by Django 4.0.1 on 2022-01-13 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('firstname', models.TextField()),
                ('lastname', models.TextField()),
                ('dob', models.DateField()),
                ('height', models.TextField()),
                ('weight', models.TextField()),
                ('phone', models.TextField()),
                ('address', models.TextField()),
                ('gender', models.TextField()),
                ('emergency_contact', models.TextField()),
            ],
        ),
    ]
