name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:


  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      env:
        DOCKER_USER: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        SECRET_KEY: ${{secrets.SECRET_KEY}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Build the Docker image
      run: |
        docker-compose build 
    - name: Docker Tag
      run: docker tag healthcare_project ${{secrets.DOCKER_USERNAME}}/healthcare_project
    - name: Docker Push
      run: docker push ${{secrets.DOCKER_USERNAME}}/healthcare_project

  deploy:

    needs: build
    runs-on: ubuntu-latest
    env:
      PEM_KEY: ${{secrets.PEM_KEY}}
    steps:
    - uses: actions/checkout@v2
    - name: Gernerate pem key file
      run: echo "$PEM_KEY" >> pem_key.pem
    - name: Make Pem executable
      run: chmod +x pem_key.pem
    - name: Login to EC2
      run: ssh -i "pem_key.pem" ec2-user@ec2-3-18-107-0.us-east-2.compute.amazonaws.com
    - name: Kill everything
      run: |
        docker kill $(docker ps -q)
        docker rm $(docker ps -a -q)
        docker rmi $(docker images -q)
    - name: Pull docker image
      run: docker pull iamsahil1910/healthcare_project 
    - name: Run the docker image
      run: docker run -dp 80:8000 iamsahil1910/healthcare_project

      
