name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:


  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      env:
        DOCKER_USER: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        SECRET_KEY: ${{secrets.SECRET_KEY}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Build the Docker image
      run: |
        export SECRET_KEY=$SECRET_KEY
        docker-compose build 
    - name: Docker Tag
      run: docker tag healthcare_project ${{secrets.DOCKER_USERNAME}}/healthcare_project
    - name: Docker Push
      run: docker push ${{secrets.DOCKER_USERNAME}}/healthcare_project
      
