name: Test API

on:
  push:
    branches: [ testing-deployed ]

jobs:


  build:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./Testing/APItesting

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install -g newman
    - run: newman run DocEasy.json


   



  