name: Test API


jobs:


  build:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./Testing/APItesting

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
    - run: npm install -g newman
    - run: newman run DocEasy.json


  